using JetBrains.Annotations;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using System;
using System.Collections.Generic;
using System.Linq;
using Terraria;
// ReSharper disable ConvertToExtensionBlock

namespace Rosemary.Content.Elk;

/*
 * "Elklang" is a meaningless conlang comprised of symbols compiled into an atlas
 * by the ElkLanguageAtlas project; References to each symbol are generated by the
 * ElkLanguageReferences project.
 * "ElkPhrases" are comprised of "ElkSymbol," phrases should always end in a
 * "Full Stop" symbol (depicted as two large four point stars stacked vertically.)
 */
public sealed class ElkPhrase : List<ElkSymbol>
{
    public Vector2 Measure(float scale)
    {
        var height = this.Sum(symbol => symbol.Height);

        return new Vector2(ElkSymbols.TOTAL_WIDTH, height) * scale;
    }
}

public record struct ElkSymbol(Vector2 Position, Rectangle Source, float Height);

public static class ElkLanguage
{
    /// <summary>
    ///     Should be used to start a new phrase over creating an instance manually.
    /// </summary>
    public static ElkPhrase NewPhrase => [];

    extension(ElkPhrase phrase)
    {
        public ElkPhrase UseOffset(Vector2 offset)
        {
            var symbol = phrase[^1];

            symbol.Position += offset;

            phrase[^1] = symbol;

            return phrase;
        }

        public ElkPhrase UseHeight(float height = 0)
        {
            var symbol = phrase[^1];

            symbol.Height = height;

            phrase[^1] = symbol;

            return phrase;
        }
    }

    // TODO: Rotation (likely using a matrix?)
    /// <summary>
    ///     Draws the given Elklang phrase similarly to standard text.
    /// </summary>
    /// <param name="sb"></param>
    /// <param name="phrase"></param>
    /// <param name="position"></param>
    /// <param name="color"></param>
    /// <param name="scale"></param>
    /// <param name="origin">
    ///     The origin of the text, based on the normalized size of the phrase.
    /// </param>
    public static void DrawPhrase(
        this SpriteBatch sb,
        ElkPhrase phrase,
        Vector2 position,
        Color color,
        float scale,
        Vector2 origin
    )
    {
        var texture = Assets.Elk.Language.ElkAtlas.Asset.Value;

        position -= origin * scale;

        foreach (var (offset, source, height) in phrase)
        {
            sb.Draw(
                texture,
                position + (offset * scale),
                source,
                color,
                0f,
                Vector2.Zero,
                scale,
                SpriteEffects.None,
                0f
            );

            position.Y += height * scale;
        }
    }

    /// <inheritdoc cref="DrawPhrase"/>
    public static void DrawPhraseOutline(this SpriteBatch sb, ElkPhrase phrase, Vector2 position, Color color, float scale, Vector2 origin, float spread = 2f, int directions = 4)
    {
        for (var i = 0; i < directions; i++)
        {
            var ratio = (float)i / directions;

            var offset = Vector2.UnitX.RotatedBy(MathF.Tau * ratio) * spread;

            sb.DrawPhrase(phrase, position + offset, color, scale, origin);
        }
    }

    /// <inheritdoc cref="DrawPhrase"/>
    public static void DrawPhraseWithOutline(this SpriteBatch sb, ElkPhrase phrase, Vector2 position, Color color, Color shadowColor, float scale, Vector2 origin, float spread = 2f, int directions = 4)
    {
        sb.DrawPhraseOutline(phrase, position, shadowColor, scale, origin, spread, directions);
        sb.DrawPhrase(phrase, position, color, scale, origin);
    }
}

[UsedImplicitly]
public static partial class ElkSymbols
{
    public const float TOTAL_WIDTH = 40;
}