<Project InitialTargets="PackageModules">

    <ItemGroup>
        <Libraries Include="$(MSBuildThisFileDirectory)daybreak-mod\src\**\*.csproj"
                   Exclude="$(MSBuildThisFileDirectory)daybreak-mod\src\Daybreak\Daybreak.csproj;$(MSBuildThisFileDirectory)daybreak-mod\src\Daybreak.CodeAnalysis\Daybreak.CodeAnalysis.csproj" />

        <Analyzers Include="$(MSBuildThisFileDirectory)daybreak-mod\src\Daybreak.CodeAnalysis\Daybreak.CodeAnalysis.csproj" />
    </ItemGroup>

    <Target Name="PackageModules" BeforeTargets="Rebuild">
        <Message Text="$(MSBuildThisFileDirectory)" Importance="high" />

        <!-- Libraries -->
        <MSBuild Projects="@(Libraries)" Targets="Build" Properties="Configuration=Release">
            <Output TaskParameter="TargetOutputs" ItemName="BuildOutput" />
        </MSBuild>

        <Copy SourceFiles="@(BuildOutput)" DestinationFolder="$(ProjectDir)lib\" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="true" />
        <Copy SourceFiles="@(BuildOutput->'%(Identity)'->Replace('.dll', '.pdb'))" DestinationFolder="$(ProjectDir)lib\" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="true" />

        <!-- Analyzers -->
        <MSBuild Projects="@(Analyzers)" Targets="Build" Properties="Configuration=Release">
            <Output TaskParameter="TargetOutputs" ItemName="BuildOutputAnalyzers" />
        </MSBuild>

        <Copy SourceFiles="@(BuildOutputAnalyzers)" DestinationFolder="$(ProjectDir)libanalyzer\" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="true" />
        <Copy SourceFiles="@(BuildOutputAnalyzers->'%(Identity)'->Replace('.dll', '.pdb'))" DestinationFolder="$(ProjectDir)libanalyzer\" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="true" />
    </Target>

</Project>