<Project>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DefineConstants>PROJECT_BUILD</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(DefineConstants.Contains(PROJECT_BUILD))'">
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="log4net" Version="3.3.0.0" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MonoMod.Utils" Version="25.0.12.0" />
    </ItemGroup>

</Project>